apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-auto-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-auto-app
  template:
    metadata:
      labels:
        app: flask-auto-app
    spec:
      containers:
      - name: flask-container
        image: sainimbalkar/flask-k8s-app
        imagePullPolicy: Always
        ports:
        - containerPort: 5000